'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const views={
  connection:['Conexão','Sua conta e o destino.','Configure a conta, o servidor, o canal e a atividade da sessão.'],
  voice:['Voz','Fala na call.','Teste a voz, ajuste o timbre e use os efeitos sonoros na call selecionada.'],
  music:['Música','Toca e controla a fila.','Busque trilhas, acompanhe a fila e mantenha a call com áudio.'],
  messages:['Mensagens','Texto e menções.','Envie mensagens, mencione pessoas e use o canal selecionado.'],
  intelligence:['Inteligência','Motor e idiomas.','Configuração do Live, idiomas, prompts e permissões do sistema.'],
  personality:['Personalidade','Tom da conversa.','Perfis, emoção base e comportamento clássico da IA.'],
  participants:['Participantes','Pessoas na conversa.','Ajuste da ordem, prioridades e contexto de quem fala.'],
  conversation:['Conversa','Pausas e turnos.','Controle de VAD, pausas, máximos e transcrições.'],
  audio:['Áudio','Buffers e saída.','Processamento de áudio, latency e filtros de saída.'],
  performance:['Performance','Métricas do sistema.','Latências, processos, logs e limites de watchdog.'],
  lab:['Laboratório','Simulação local.','Teste de pausa, comportamento e cenários de interrupção.'],
  history:['Histórico','Transcrições e contexto.','Sessões, memória e retenção de conversas locais.'],
  costs:['Custos','Uso e estimativas.','Custo de tokens, cálculo e carteira do provedor.'],
  tools:['Ferramentas','Permissões e utilidades.','Ferramentas do sistema e regras de autorização.'],
  prompts:['Prompts','Instruções da IA.','Prompt do sistema, hierarquia e contexto ativo.'],
  memory:['Memória','Contexto persistente.','Notas, resumos e retenção da conversa.'],
  security:['Segurança','Controle local.','Proteções do selfbot, acesso e ações de sessão.'],
  developer:['Desenvolvedor','Diagnóstico técnico.','Replay, timeline e inspeção do sistema.'],
  recordings:['Gravações','Arquivos locais.','Gravações da call, revisões e inspeção de áudio.']
};
let data=null,status=null,catalog=null,draft={},view='connection',rendered='',busy=false,polling=false,replay=[];
const actionHistory=[];
const fields={
  enabled:['Conversa Live ativa','bool'],provider:['Provider','select',['gemini','cascade']],model:['Modelo Live','text'],fallback:['Fallback após falhas','select',['none','cascade'],'Cascade usa STT + LLM + Edge e preserva as políticas desta sessão.'],
  mode:['Participação','select',['observer','conversational','participative']],onlyWhenCalled:['Só responder quando chamado','bool'],wakeWords:['Nomes de chamada','list','Separe por vírgulas.'],
  replyLanguage:['Idioma de resposta','select',['auto','pt-BR','es','en']],
  profile:['Perfil','select',['Casual','Gamer','Amigo','Streamer','Assistente','Personalizado']],personality:['Personalidade personalizada','textarea'],
  humor:['Humor','number',0,100],energy:['Energia','number',0,100],curiosity:['Curiosidade','number',0,100],spontaneity:['Espontaneidade','number',0,100],formality:['Formalidade','number',0,100],sarcasm:['Sarcasmo','number',0,100],concision:['Concisão','number',0,100],
  voice:['Voz Gemini','text'],fallbackVoice:['Voz Edge / Cascade','select',['francisca','thalita','antonio']],speed:['Ritmo sugerido ao modelo','number',.5,2,.05],volume:['Volume de saída','number',0,2,.05],pitch:['Pitch em semitons','number',-6,6,.5],style:['Estilo de fala','text'],intensity:['Intensidade','number',0,100],pronunciation:['Guia de pronúncia','textarea'],
  silenceMs:['Pausa natural · ms','number',200,2500],incompleteMs:['Pausa com frase incompleta · ms','number',300,4000],vadMs:['Voz contínua para confirmar · ms','number',60,600],vadThreshold:['Limiar de energia RMS','number',50,5000],
  maxUtteranceSeconds:['Duração máxima de entrada · s','number',2,120],maxResponseSeconds:['Duração máxima de resposta · s','number',2,60],maxCharacters:['Máximo de caracteres de resposta','number',50,4000],
  prebufferMs:['Prebuffer de saída · ms','number',40,1000],maxBufferMs:['Limite do buffer de saída · ms','number',1000,15000],maxInputBufferMs:['Limite de entrada pendente · ms','number',300,5000],maxPendingMs:['Idade máxima de fala pendente · ms','number',1000,15000],
  maxParticipants:['Participantes simultâneos','number',1,32],priorityUserId:['Discord ID prioritário','text'],
  normalize:['Normalização dinâmica','bool'],compressor:['Compressor','bool'],limiter:['Limiter','bool'],noiseReduction:['Redução de ruído na saída','bool'],equalizer:['Ganho de presença · dB / 3 kHz','number',-12,12,.5],
  cooldownMs:['Cooldown · ms','number',0,30000],responsesPerMinute:['Respostas por minuto','number',1,60],interruptionsPerMinute:['Interrupções por minuto','number',1,120],
  allowUsers:['Allowlist · IDs de usuários','list'],denyUsers:['Denylist · IDs de usuários','list'],allowRoles:['Allowlist · IDs de funções','list'],denyRoles:['Denylist · IDs de funções','list'],
  tools:['Ferramentas habilitadas','list','clock, calculator'],toolUsers:['Usuários autorizados a ferramentas','list'],toolRoles:['Funções autorizadas a ferramentas','list'],
  retainTranscripts:['Mostrar transcrições na sessão','bool'],permanentMemory:['Permitir memória permanente','bool'],memoryUsers:['Usuários autorizados à memória','list'],clearOnLeave:['Apagar sessão ao sair da call','bool'],maxHistory:['Turnos no contexto recente','number',2,200],maxSummaryChars:['Tamanho do resumo · caracteres','number',200,8000],
  reconnectAttempts:['Tentativas de reconexão','number',0,8],idleSessionSeconds:['Fechar provider ocioso após · s','number',30,1800],watchdogMb:['Limite RSS do processo · MB','number',128,8192],watchdogLagMs:['Limite de atraso do processo · ms','number',250,10000],
  developer:['Detalhar frames no monitor','bool'],inputPrice:['USD por milhão de tokens de entrada','number',0,1000,.01],outputPrice:['USD por milhão de tokens de saída','number',0,1000,.01],
  systemPrompt:['Instruções do administrador','textarea'],autoJoinGuild:['Servidor para entrada automática · ID','text'],autoJoinChannel:['Canal de voz automático · ID','text']
};
async function api(url,body){const r=await fetch(url,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error||'A operação falhou.');return result;}
function feedback(text,error=false){$('#feedback').hidden=false;$('#feedback').textContent=text;$('#feedback').classList.toggle('error',error);if(actionHistory[0]?.text!==text){actionHistory.unshift({text,at:new Date().toLocaleTimeString('pt-BR')});actionHistory.length=Math.min(actionHistory.length,20);$('#actionHistory').innerHTML=actionHistory.map(item=>`<li class="event"><time>${esc(item.at)}</time><span>${esc(item.text)}</span></li>`).join('');}}
function settings(){return {...data?.config,...draft};}
function form(keys){const c=settings();return '<div class="field-grid">'+keys.map(key=>{const f=fields[key],[label,type]=f,value=c[key];let input;
  if(type==='bool')return `<label class="field toggle" for="f-${key}"><span>${esc(label)}<small>${esc(fieldHelp[key]||'')}</small></span><input id="f-${key}" data-setting="${key}" type="checkbox" ${value?'checked':''}></label>`;
  if(type==='select')input=`<select id="f-${key}" data-setting="${key}">${f[2].map(x=>`<option ${x===value?'selected':''} value="${esc(x)}">${esc(optionLabels[x]||x)}</option>`).join('')}</select>`;
  else if(type==='textarea')input=`<textarea id="f-${key}" data-setting="${key}" maxlength="4000">${esc(value)}</textarea>`;
  else input=`<input id="f-${key}" data-setting="${key}" type="${type==='number'?'number':'text'}" value="${esc(Array.isArray(value)?value.join(', '):value)}" ${type==='number'?`min="${f[2]}" max="${f[3]}" step="${f[4]||1}"`:'maxlength="4000"'}>`;
  const hint=fieldHelp[key]||'';
  return `<label class="field ${type==='textarea'?'wide':''}" for="f-${key}">${esc(label)}${input}${hint?`<small>${esc(hint)}</small>`:''}</label>`;
}).join('')+'</div>';}
function card(title,body,full=false){return `<article class="card ${full?'full':''}"><div class="card-head"><h2>${esc(title)}</h2></div>${body}</article>`;}
function placeholder(key){return `<div data-live="${key}"></div>`;}
function sectionForms(groups){return '<div class="grid">'+groups.map(([title,keys])=>card(title,form(keys))).join('')+'</div>';}
function render(force=false){if(!data)return;if(!force&&rendered===view){renderLive();if(view==='recordings')loadRecordings();return;}rendered=view;const v=views[view];$('#title').textContent=v[1];$('#description').textContent=v[2];$('#breadcrumb').textContent=v[0];
  $('#navigation').innerHTML=Object.entries(views).map(([key,[name]],i)=>`<a href="#${key}" ${view===key?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(name)}</a>`).join('');let html=renderClassic(view);
  if(view==='pipeline')html=placeholder('stats')+'<div class="grid">'+card('Tudo no mesmo painel','<p>Conecte sua conta, escolha o destino acima e use as funções no menu. A seção Voz reúne a fala manual e a conversa Live; Personalidade reúne os ajustes antigos e novos.</p><div class="quick-links"><a href="#connection">Conexão Discord<small>Conta, token, convite e presença</small></a><a href="#voice">Call e voz<small>Falar, repetir e ajustar timbre</small></a><a href="#music">Música<small>Buscar, tocar e controlar a fila</small></a><a href="#messages">Mensagens<small>Enviar, mencionar e resumir</small></a><a href="#intelligence">Inteligência e idiomas<small>PT-BR · Español · English</small></a><a href="#security">Segurança<small>Entender os bloqueios e rearmar</small></a></div>',true)+card('Sessão atual',placeholder('engine'))+card('Últimos eventos',placeholder('timeline'))+card('Como a conversa funciona',placeholder('pipeline'),true)+'</div>';
  if(view==='intelligence')html=sectionForms([['Idiomas · Live e clássico',['replyLanguage']],['Motor da conversa Live',['enabled','provider','model','fallback']],['Participação',['mode','onlyWhenCalled','wakeWords']],['Entrada automática',['autoJoinGuild','autoJoinChannel']],['Recuperação',['reconnectAttempts','idleSessionSeconds']]])+'<div class="small-gap">'+card('Entender três idiomas','<p>A entrada detecta português brasileiro, espanhol e inglês, sem precisar trocar a configuração a cada fala. No modo Automático a resposta acompanha o idioma atual. Se escolher um idioma fixo, a IA continua entendendo os três e responde no idioma escolhido.</p><p class="small-gap">Exemplos: “Neve, como você está?”, “Neve, ¿cómo estás?” e “Neve, how are you?”. Os nomes de chamada e as permissões continuam valendo.</p>')+'</div><div class="small-gap">'+card('Presets',placeholder('presets'))+'</div>';
  if(view==='personality')html=sectionForms([['Identidade · Live',['profile','personality']],['Tom e atitude · Live',['humor','energy','curiosity','spontaneity','formality','sarcasm','concision']]])+classicPersonalityCards();
  if(view==='participants')html='<div class="grid">'+card('Pessoas na conversa',placeholder('participants'),true)+card('Ordem da conversa',form(['maxParticipants','priorityUserId']))+card('Como os fluxos se encontram','<p>Cada participante tem um fluxo de áudio e contexto identificados pelo Discord ID. A fila aguarda o fim das falas simultâneas e prioriza o ID configurado. Voz confirmada interrompe a resposta em reprodução; ruído isolado não interrompe.</p>')+'</div>';
  if(view==='conversation')html=sectionForms([['Início e fim da fala',['vadMs','vadThreshold','silenceMs','incompleteMs']],['Turnos e respostas',['maxUtteranceSeconds','maxResponseSeconds','maxCharacters','maxPendingMs']]])+'<div class="small-gap">'+card('Conversa em andamento',placeholder('conversation'))+'</div>';
  if(view==='voice')html=classicVoiceCards()+'<div class="small-gap">'+sectionForms([['Timbre e expressão · Live',['voice','fallbackVoice','style','speed','intensity','pronunciation']],['Saída de áudio · Live',['volume','pitch','normalize','compressor','limiter']]])+'</div><div class="small-gap">'+card('Teste de voz Live na call','<p>Usa a configuração Live salva. O teste consome a API e é ouvido pelos participantes da call selecionada.</p><label class="field small-gap" for="testText">Frase de teste<input id="testText" maxlength="300" value="Olá! Vamos conversar? Estou ouvindo vocês."></label><div class="actions"><button id="testVoice" class="primary">Testar voz Live na call</button></div>')+'</div>';
  if(view==='audio')html=sectionForms([['Buffers e latência',['prebufferMs','maxBufferMs','maxInputBufferMs']],['Processamento de saída',['noiseReduction','equalizer','normalize','compressor','limiter']]])+'<div class="small-gap">'+card('Filas e transporte',placeholder('queues'))+'</div>';
  if(view==='performance')html=placeholder('stats')+'<div class="grid">'+card('Latências Live · janela de até 200 amostras',placeholder('metrics'),true)+card('Latências clássicas e mensagens',placeholder('classicMetrics'),true)+card('Processo e watchdog',placeholder('resources'))+card('Limites do processo',form(['watchdogMb','watchdogLagMs']))+'</div>';
  if(view==='lab')html='<div class="grid">'+card('Simular uma pausa','<label class="field" for="labText">Frase da pessoa<textarea id="labText" maxlength="4000" placeholder="Neve, eu queria te perguntar uma coisa, mas…"></textarea></label><label class="field toggle small-gap">Outra pessoa está falando<input id="labOther" type="checkbox"></label><label class="field toggle small-gap">Já existe uma conversa dirigida à IA<input id="labEngaged" type="checkbox"></label><div class="actions"><button id="runLab" class="primary">Analisar segmento</button></div><output id="labResult" class="lab-result"></output>')+card('O que é medido','<p>O laboratório usa a mesma regra local de pausa e participação da call. Frases incompletas ou outra pessoa falando estendem a pausa. O resultado é uma heurística, não uma classificação semântica do Gemini.</p><p class="small-gap">Não conecta ao Discord, não transmite áudio e não consome tokens.</p>')+card('Perfis de execução',placeholder('presets'),true)+'</div>';
  if(view==='history')html='<div class="grid">'+card('Transcrições finalizadas',placeholder('history'),true)+card('Retenção local',form(['retainTranscripts','clearOnLeave']))+card('Sessões anteriores',placeholder('archives'))+'</div>';
  if(view==='costs')html='<div class="grid">'+card('Uso reportado pelo Gemini',placeholder('usage'))+card('Sua tabela de preços',form(['inputPrice','outputPrice'])+'<p class="muted small-gap">Preencha o preço da modalidade de áudio do seu contrato. Estimativa indicativa; não é uma fatura. Zero significa preço não configurado.</p>')+'</div>';
  if(view==='tools')html='<div class="grid">'+card('Ferramentas disponíveis','<div class="mini-row"><span>clock</span><span>Data e hora UTC</span></div><div class="mini-row"><span>calculator</span><span>Aritmética sem execução de código</span></div><p class="small-gap">Web, documentos, jogos e APIs externas não estão habilitados. Novas ferramentas devem declarar sua permissão e confirmação antes de qualquer ação sensível.</p>')+card('Autorizações',form(['tools','toolUsers','toolRoles']))+'</div>';
  if(view==='prompts')html='<div class="grid">'+card('Instruções editáveis',form(['systemPrompt']))+card('Hierarquia aplicada','<p>SYSTEM RULES → PERMISSION RULES → PERSONALITY → CONTEXT → USER CONTENT</p><p class="small-gap">O aplicativo verifica permissões antes de enviar áudio, executar ferramentas e reproduzir respostas. Conteúdo da conversa não altera configurações.</p>')+card('Prompt efetivo',placeholder('prompt'),true)+'</div>';
  if(view==='memory')html='<div class="grid">'+card('Contexto da call',form(['maxHistory','maxSummaryChars','clearOnLeave'])+'<p class="muted small-gap">Contexto antigo vira um resumo extrativo limitado. Gravar áudio é uma ação separada na área Gravações; limpar o contexto não apaga os WAVs.</p><div class="actions"><button data-control="clear">Apagar contexto temporário</button></div>')+card('Política de memória permanente',form(['permanentMemory','memoryUsers']))+card('Adicionar nota autorizada','<p class="muted">Somente notas inseridas aqui são persistidas. O modelo não grava memórias sozinho.</p><label class="field small-gap">Discord ID<input id="memoryUser" maxlength="80"></label><label class="field small-gap">Informação autorizada<textarea id="memoryText" maxlength="1000"></textarea></label><div class="actions"><button id="saveMemory" class="primary">Salvar nota</button></div>')+card('Notas permanentes',placeholder('notes'))+'</div>';
  if(view==='security')html='<div class="grid">'+card('Estado de proteção',placeholder('security'),true)+card('Permissões de participantes',form(['allowUsers','denyUsers','allowRoles','denyRoles'])+'<p class="muted small-gap">Denylist tem precedência. Allowlists vazias permitem todos os participantes humanos. Funções são verificadas no servidor da call.</p>')+card('Limites de resposta',form(['responsesPerMinute','interruptionsPerMinute','cooldownMs','maxCharacters','maxResponseSeconds']))+card('Privacidade',form(['retainTranscripts','clearOnLeave','permanentMemory']))+card('Credenciais e acesso','<p>Chaves ficam no .env e nunca são retornadas por esta API. O painel aceita somente conexões locais e rejeita requisições de outras origens. Kill Switch encerra as calls e bloqueia novas respostas até rearmar.</p>')+'</div>';
  if(view==='developer')html='<div class="grid">'+card('Monitor',form(['developer'])+placeholder('debug'))+card('Replay técnico','<p>Timeline de eventos sem conteúdo de voz. Exporte para reproduzir a ordem e os intervalos; áudio não é gravado.</p><div class="actions"><button id="exportReplay">Exportar JSON</button></div><label class="field small-gap">Abrir timeline<input type="file" id="replayFile" accept="application/json,.json"></label><label class="field small-gap">Evento<input type="range" id="replayIndex" min="0" max="0" value="0"></label><pre id="replayEvent" class="code small-gap">Nenhum replay aberto.</pre>')+card('Timeline ao vivo',placeholder('timeline'),true)+'</div>';
  if(view==='recordings')html=recordingsView();
  $('#content').innerHTML=html;renderVoiceOptions();renderLive();renderDraft();if(view==='recordings')loadRecordings();
}
function total(name){return data.sessions.reduce((n,s)=>n+(s.telemetry.counters[name]||0),0);}
function current(){return data.sessions.find(s=>s.guildId===status?.guildId)||data.sessions[0];}
const empty=text=>`<p class="empty">${esc(text)}</p>`;
function rows(items){return items.map(([label,value])=>`<div class="mini-row"><span>${esc(label)}</span><span>${esc(value)}</span></div>`).join('');}
function table(headers,items){return items.length?'<div class="table-scroll"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+items.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':empty('Sem dados ainda. As medições aparecem durante a conversa.');}
function classicMetricsTable(){
  const labels=[['Transcrição','stt'],['Primeiro texto da IA','firstToken'],['Primeiro trecho pronto para voz','firstSentence'],['IA · resposta completa','llm'],['Síntese · primeiro áudio','firstAudio'],['Síntese · áudio completo','tts'],['Fim da fala → áudio na call','voiceReply'],['Mensagem recebida → áudio na call','textVoiceReply'],['Mensagem recebida → texto enviado','reply']];
  const ms=value=>Number.isFinite(value)?value+' ms':'—';
  return '<p class="muted">Até 30 amostras por etapa. P50 é a mediana; 95% das medições ficam até o P95. As etapas se sobrepõem e não devem ser somadas.</p>'+table(['Etapa','Amostras','Última','Média','P50','P95','Maior'],labels.map(([label,key])=>{
    const v=status?.metrics?.[key]||{};
    return [label,v.samples||0,ms(v.last),ms(v.average),ms(v.p50),ms(v.p95),ms(v.max)];
  }));
}
function renderLive(){if(!data)return;const s=current(),o=data.config,events=s?.telemetry.events||[],metrics=s?.telemetry.latency||{};
  const content={
    stats:()=>'<div class="stats">'+[['Estado',s?.state||'OFFLINE',s?.safeMode?'Safe Mode':o.mode],['Latência P50',metrics.total?metrics.total.p50+' ms':'—','Fim da fala → playback'],['Respostas',total('responses'),'Nesta execução'],['Interrupções',total('interruptions'),'Voz confirmada']].map(([label,value,hint])=>`<div class="stat"><div class="label">${esc(label)}</div><div class="value ${label==='Estado'?'accent':''}">${esc(value)}</div><small>${esc(hint)}</small></div>`).join('')+'</div>',
    pipeline:()=>!o.enabled?'<p>Modo clássico: microfone → transcrição → resposta de texto → voz → Discord. Os trechos de áudio usam arquivos temporários, removidos após o processamento.</p>':'<p>Entrada PCM 16 kHz · '+(s?.provider==='cascade'||o.provider==='cascade'?'transcrição + IA + Edge':'áudio nativo Gemini')+' · saída PCM 24 kHz → Opus</p><div class="pipeline">'+[['Discord','Recepção','LISTENING'],['Participante','Fluxo separado','LISTENING'],['VAD','Voz e silêncio','LISTENING'],['Endpoint','Pausa e contexto','WAITING'],[s?.provider==='cascade'||o.provider==='cascade'?'Cascade':'Gemini','Geração da resposta','PROCESSING'],['Safety','Políticas locais','PROCESSING'],['Playback','Buffer limitado','SPEAKING']].map(([name,caption,state],i)=>`${i?'<span class="arrow">›</span>':''}<div class="node ${s?.state===state?'active':''}">${name}<small>${caption}</small></div>`).join('')+'</div>',
    engine:()=>`<div class="engine"><div class="status-orb" aria-hidden="true"></div><div><strong>${esc(s?.state||'Aguardando a call')}</strong><small>${esc(o.model)}</small></div></div>`+rows([['Provider',s?.provider||o.provider],['Voz',o.voice],['Participação',o.mode],['Resposta atual',s?.responseId||'—'],['Configuração pendente',s?.pendingConfiguration?'Sim':'Não']]),
    timeline:()=>events.length?'<div class="events">'+events.slice(-35).reverse().map(e=>`<div class="event"><time>${esc(new Date(e.at).toLocaleTimeString('pt-BR'))}</time><b>${esc(e.type)}</b><small>${esc(e.reason||e.state||(e.responseId?'#'+e.responseId:''))}</small></div>`).join('')+'</div>':empty('A timeline começa quando uma pessoa fala.'),
    participants:()=>table(['Pessoa / Discord ID','Estado','Provider','Entrada','Saída'],(s?.participants||[]).map(p=>[p.name+' / '+p.id,p.phase,p.connected?'Conectado':'Aguardando',p.inputBytes+' B',p.outputBytes+' B'])),
    conversation:()=>!o.retainTranscripts?empty('Exibição de transcrições desligada em Privacidade.'):('<div class="conversation">'+(s?.participants||[]).filter(p=>p.partial).map(p=>`<div class="bubble"><strong>${esc(p.name)} · parcial</strong><p>${esc(p.partial)}</p></div>`).join('')+(s?.memory.turns||[]).slice(-8).map(t=>`<div class="bubble"><strong>${esc(t.role==='assistant'?'Neva7':t.userId)} · final</strong><p>${esc(t.text)}</p></div>`).join('')+'</div>'),
    history:()=>!o.retainTranscripts?empty('Transcrições completas não são exibidas. Ative a opção de privacidade para acompanhar esta sessão.'):content.conversation(),
    archives:()=>table(['Servidor','Turnos retidos','Estado final'],data.archives.map(a=>[a.guildId,a.memory.count,a.state])),
    queues:()=>rows([['Entrada pendente',(s?.participants||[]).reduce((n,p)=>n+p.inputBytes,0)+' B'],['Saída pendente',(s?.participants||[]).reduce((n,p)=>n+p.outputBytes,0)+' B'],['Overflows de entrada',total('inputOverflows')],['Overflows de saída',total('outputOverflows')],['Gaps de captura',total('captureGaps')],['Packet loss','Não exposto pela biblioteca']]),
    metrics:()=>table(['Etapa','Amostras','Última','P50','P95','P99'],Object.entries(metrics).map(([key,v])=>[key,v.samples,v.last+' ms',v.p50+' ms',v.p95+' ms',v.p99+' ms'])),
    classicMetrics:classicMetricsTable,
    resources:()=>rows([['Memória RSS',(s?.resources.rssMb||0)+' MB'],['CPU',(s?.resources.cpuPercent||0)+'%'],['Atraso do event loop',(s?.resources.eventLoopLagMs||0)+' ms'],['Erros',total('errors')],['Loops detectados',total('loops')]]),
    usage:()=>rows([['Tokens de entrada',data.sessions.reduce((n,x)=>n+x.usage.input,0)],['Tokens de saída',data.sessions.reduce((n,x)=>n+x.usage.output,0)],['Total reportado',data.sessions.reduce((n,x)=>n+x.usage.total,0)],['Estimativa USD',o.inputPrice||o.outputPrice?data.sessions.reduce((n,x)=>n+x.estimatedCost,0).toFixed(5):'Preços não configurados']]),
    prompt:()=>`<pre class="code">${esc(data.prompt)}</pre>`,
    presets:()=>'<div class="grid">'+data.presets.map(name=>`<div class="preset ${o.preset===name?'selected':''}"><h3>${esc(name)}</h3><p>${esc({'Ultra Low Latency':'Pausas e prebuffer curtos.','Natural':'Equilíbrio entre fluidez e pausas.','High Quality':'Mais tolerância a pausas e jitter.','Economy':'Respostas curtas e menos turnos.','Development':'Monitor técnico detalhado.'}[name])}</p><button data-preset="${esc(name)}">Aplicar preset</button></div>`).join('')+'</div>',
    notes:()=>data.permanent.length?'<div class="note-list">'+data.permanent.map(n=>`<article><strong>${esc(n.userId)} · servidor ${esc(n.guildId)}</strong><p>${esc(n.text)}</p><button data-delete-note="${esc(n.id)}">Apagar nota</button></article>`).join('')+'</div>':empty('Nenhuma memória permanente salva.'),
    security:()=>rows([['Kill Switch',o.killed?'ATIVADO':'Desarmado'],['Safe Mode',o.safeMode||s?.safeMode?'ATIVADO':'Normal'],['Silent Mode',s?.silent?'Aguardando chamada direta':'Normal'],['Fallback',s?.fallback?'Cascade ativo':'Não acionado'],['Gravação local',status?.recordingActive?.length?'ATIVA · salvando áudio no PC':'Manual · consulte a área Gravações'],['Áudio Live / Cascade','Em memória; salvo em disco somente ao iniciar gravação'],['Áudio clássico e fala manual','Arquivos temporários + gravação manual, se ativa'],['Memória permanente',o.permanentMemory?'Somente usuários autorizados':'Desligada']]),
    debug:()=>`<pre class="code small-gap">${esc(JSON.stringify({state:s?.state||'OFFLINE',responseId:s?.responseId,participants:s?.participants.map(({partial,...p})=>p),counters:s?.telemetry.counters,capabilities:data.capabilities},null,2))}</pre>`
  };
  document.querySelectorAll('[data-live]').forEach(el=>{el.innerHTML=content[el.dataset.live]?.()||'';});
  renderNotices(s);renderClassicLive();renderConnectionControls();renderRecordings();
}
function renderNotices(s){const o=data.config,notice=[];const item=(title,body,actions='')=>`<div class="notice-row"><div><strong>${esc(title)}</strong><p>${esc(body)}</p></div><div class="actions">${actions}</div></div>`;
  if(!status?.online)notice.push(item('Discord desconectado',status?.connectionError||'Configure a conta aqui e reinicie o programa para conectar.','<a class="button-link" href="#connection">Configurar conexão</a>'));
  if(status?.connection?.restartRequired)notice.push(item('Conexão salva · reinício pendente','Reinicie o programa com npm.cmd start para aplicar a conta e o token escolhidos.'));
  if(o.enabled&&!data.botMode)notice.push(item('Live precisa de bot oficial','A conta atual está em modo pessoal. Escolha Bot oficial em Conexão Discord ou ative o modo clássico para continuar com as funções existentes.','<a class="button-link" href="#connection">Configurar bot oficial</a><button data-use-classic>Usar modo clássico</button>'));
  if(o.enabled&&data.botMode&&o.provider==='gemini'&&!data.keyConfigured)notice.push(item('Chave Gemini pendente','Configure GEMINI_API_KEY no arquivo .env e reinicie para conversar com Gemini.'));
  if(o.enabled&&(o.provider==='cascade'||s?.fallback)&&!data.cascadeConfigured)notice.push(item('Chave Cascade pendente','Configure GROQ_API_KEY ou OPENAI_API_KEY no arquivo .env e reinicie.'));
  if(o.killed||o.safeMode||s?.safeMode)notice.push(item(o.killed?'Kill Switch ativo':'Safe Mode ativo',o.killed?'As calls foram encerradas e novas respostas estão bloqueadas. Rearmar libera a conversa; depois escolha a call.':'As respostas estão pausadas. Confira os últimos eventos e clique em Rearmar para liberar a conversa.','<button data-control="resume" class="primary">Rearmar conversa</button><a class="button-link" href="#developer">Ver timeline</a>'));
  if(s?.fallback)notice.push(item('Cascade em uso','O Gemini falhou e a conversa usa transcrição + IA + Edge. Rearmar volta a tentar o provider principal.'));
  const html=notice.join('');$('#notice').hidden=!notice.length;if($('#notice').innerHTML!==html)$('#notice').innerHTML=html;
  $('#modeBadge').textContent=s?.fallback?'CASCADE FALLBACK':o.enabled?(o.provider==='cascade'?'CASCADE':'GEMINI LIVE'):'MODO CLÁSSICO';
}
function joinBlockReason(){const o=data?.config;if(!status?.online)return 'Conecte a conta em Conexão Discord.';if(o?.killed||o?.safeMode||current()?.safeMode)return 'Use Rearmar conversa para liberar a entrada.';if(o?.enabled&&!data.botMode)return 'Configure um bot oficial ou escolha Usar modo clássico.';if(!status?.guildId)return 'Escolha um servidor.';if(!$('#channel').value)return 'Escolha um canal de voz.';return '';}
function renderConnectionControls(){const reason=joinBlockReason();$('#join').disabled=!!reason;$('#join').title=reason||'Conecta a conta à call selecionada.';$('#leave').disabled=!status?.inCall;$('#destinationHelp').textContent=reason||'Destino pronto. Entrar conecta à call; mensagens usam o canal de texto selecionado.';$('#guild').disabled=!status?.online;$('#textChannel').disabled=!status?.online||!status?.guildId;$('#channel').disabled=!status?.online||!status?.guildId;if($('#testVoice'))$('#testVoice').disabled=!status?.inCall||!data.botMode||data.config.killed||data.config.safeMode||!!current()?.safeMode;}
function renderDraft(){const count=Object.keys(draft).length;$('#draftStatus').textContent=count?`${count} alteração(ões) ainda não aplicada(s)`:'Configurações salvas neste computador';$('#save').disabled=!count||busy;$('#discard').disabled=!count||busy;}
async function command(action,value={}){if(busy)return;busy=true;renderDraft();try{const result=await api('/api/live/action',{action,value});data=result;feedback(result.message);if(action==='settings'){draft={};rendered='';}render();}catch(e){feedback(e.message,true);}finally{busy=false;renderDraft();}}
async function loadCatalog(){const previous=$('#channel').value;catalog=await api('/api/catalog');$('#guild').innerHTML='<option value="">Escolha um servidor</option>'+catalog.servers.map(g=>`<option value="${esc(g.id)}" ${g.id===status?.guildId?'selected':''}>${esc(g.name)}</option>`).join('');$('#channel').innerHTML='<option value="">Escolha uma call</option>'+catalog.voiceChannels.map(c=>`<option value="${esc(c.id)}" ${c.id===(status?.voiceChannelId||previous)?'selected':''}>${esc(c.name)}</option>`).join('');$('#textChannel').innerHTML='<option value="">Escolha um canal</option>'+catalog.textChannels.map(c=>`<option value="${esc(c.id)}" ${c.id===status?.textChannelId?'selected':''}>#${esc(c.name)}</option>`).join('');renderVoiceOptions();renderConnectionControls();if(view==='personality'&&$('#classicEmotion'))$('#classicEmotion').innerHTML=(catalog.emotions||[]).map(x=>`<option value="${esc(x)}" ${x===status?.emotion?'selected':''}>${esc(x)}</option>`).join('');}
async function poll(){if(polling)return;polling=true;try{const [live,s,effects]=await Promise.all([api('/api/live'),api('/api/status'),api('/api/sound-effects').catch(()=>({effects:[]}))]);const refreshCatalog=!catalog||status?.online!==s.status.online||status?.guildId!==s.status.guildId;data=live;status=s.status;status.soundEffects = effects.effects || [];$('#sync').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR');$('#discordState').textContent=status.online?'Discord conectado':'Discord desconectado';$('#discordDot').classList.toggle('on',status.online);$('#callState').textContent=status.inCall?status.call:'Fora da call';render();if(refreshCatalog)await loadCatalog();}catch(e){$('#sync').textContent='Sem conexão';feedback(e.message,true);}finally{polling=false;}}
document.addEventListener('input',e=>{const key=e.target.dataset.setting;if(!key)return;const type=fields[key][1];const value=type==='bool'?e.target.checked:type==='number'?Number(e.target.value):type==='list'?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value;if(JSON.stringify(data.config[key])===JSON.stringify(value))delete draft[key];else draft[key]=value;renderDraft();});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
  if(b.dataset.control)await command(b.dataset.control);
  if(b.dataset.preset){if(Object.keys(draft).length){feedback('Aplique ou descarte suas alterações antes de trocar o preset.',true);return;}await command('preset',{name:b.dataset.preset});render(true);}
  if(b.dataset.deleteNote)await command('memoryDelete',{id:b.dataset.deleteNote});
  if(b.id==='saveMemory'){if(!status.guildId)throw new Error('Selecione o servidor da memória.');await command('memorySave',{guildId:status.guildId,userId:$('#memoryUser').value.trim(),text:$('#memoryText').value});}
  if(b.id==='runLab'){const result=await api('/api/live/lab',{text:$('#labText').value,otherSpeaking:$('#labOther').checked,engaged:$('#labEngaged').checked});$('#labResult').textContent=`Pausa: ${result.endpointMs} ms\nResponderia: ${result.wouldRespond?'sim':'não'}\nUso de rede/API: não`;}
  if(b.id==='testVoice'){b.disabled=true;try{const result=await api('/api/live/test-voice',{guildId:status.guildId,text:$('#testText').value});feedback(result.message);}finally{b.disabled=false;}}
  if(b.id==='exportReplay'){const result=await api('/api/live/replay');const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='neva7-timeline.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
}catch(error){feedback(error.message,true);}});
document.addEventListener('change',async e=>{if(e.target.id!=='replayFile')return;try{const file=e.target.files[0];if(!file||file.size>1000000)throw new Error('Use uma timeline JSON com até 1 MB.');const value=JSON.parse(await file.text());replay=(value.sessions||[]).flatMap(s=>s.events||[]).slice(0,2000).sort((a,b)=>a.at-b.at);$('#replayIndex').max=Math.max(0,replay.length-1);$('#replayIndex').value=0;showReplay();}catch(error){feedback(error.message,true);}});
function showReplay(){const i=Number($('#replayIndex').value),e=replay[i];$('#replayEvent').textContent=e?`Evento ${i+1}/${replay.length} · +${e.at-replay[0].at} ms\n${JSON.stringify(e,null,2)}`:'Timeline vazia.';}
document.addEventListener('input',e=>{if(e.target.id==='replayIndex')showReplay();});
$('#save').onclick=()=>command('settings',draft);$('#discard').onclick=()=>{draft={};render(true);};$('#refresh').onclick=async()=>{await poll();await loadCatalog().catch(e=>feedback(e.message,true));};
$('#guild').onchange=async()=>{resetMemberSearch();changingDestination=true;renderClassicLive();try{const result=await api('/api/action',{action:'selectServer',value:{id:$('#guild').value}});status=result.status;renderLive();await poll();await loadCatalog();}catch(e){feedback(e.message,true);}finally{changingDestination=false;renderClassicLive();}};
$('#textChannel').onchange=async()=>{changingDestination=true;renderClassicLive();try{const result=await api('/api/action',{action:'selectText',value:{id:$('#textChannel').value}});status=result.status;renderLive();await poll();}catch(e){feedback(e.message,true);}finally{changingDestination=false;renderClassicLive();}};
$('#channel').onchange=renderConnectionControls;
$('#join').onclick=async()=>{try{if(!$('#channel').value)throw new Error('Escolha uma call.');$('#join').disabled=true;await api('/api/action',{action:'join',value:{channelId:$('#channel').value}});await poll();}catch(e){feedback(e.message,true);$('#join').disabled=false;}};
$('#leave').onclick=async()=>{try{await api('/api/action',{action:'leave'});await poll();}catch(e){feedback(e.message,true);}};
function navigate(){const aliases={sessao:'voice',musica:'music',mensagens:'messages',configuracoes:'connection',conta:'connection',presenca:'connection',seguranca:'security',inteligencia:'intelligence',personalidade:'personality',participantes:'participants',conversa:'conversation',audio:'audio',performance:'performance',laboratorio:'lab',historico:'history',custos:'costs',ferramentas:'tools',prompts:'prompts',memoria:'memory',desenvolvedor:'developer',gravacoes:'recordings'};const key=aliases[location.hash.slice(1)]||location.hash.slice(1);view=Object.hasOwn(views,key)?key:'connection';resetMemberSearch();render(true);}
window.addEventListener('hashchange',navigate);window.addEventListener('beforeunload',e=>{if(Object.keys(draft).length){e.preventDefault();e.returnValue='';}});
$('#shutdownDialog').addEventListener('close',()=>{if($('#shutdownDialog').returnValue==='confirm')classicAction('shutdown');});
navigate();poll().catch(e=>feedback(e.message,true));setInterval(poll,1500);
