'use strict';
const optionLabels={auto:'Automático · idioma de quem fala','pt-BR':'Português brasileiro',es:'Espanhol',en:'Inglês',gemini:'Gemini · áudio nativo',cascade:'Cascade · transcrição + IA + voz',none:'Desligado',observer:'Observador · escuta sem responder',conversational:'Conversa · responde ao ser chamado',participative:'Participativo · pode intervir no assunto'};
const fieldHelp={
  enabled:'Liga a conversa contínua com bot oficial. Desligue para usar a captura e as respostas do modo clássico. Música e mensagens continuam no painel.',
  provider:'Gemini entende o áudio diretamente. Cascade primeiro transcreve, gera o texto e depois cria a voz.',
  model:'Identificador do modelo de áudio Live disponível para sua chave Gemini. Só se aplica ao provider Gemini.',
  fallback:'Escolha Cascade para tentar o motor alternativo após falhas do Gemini. Precisa de GROQ_API_KEY ou OPENAI_API_KEY.',
  replyLanguage:'A entrada reconhece PT-BR, ES e EN automaticamente. Automático responde no idioma da fala; uma opção fixa muda apenas o idioma da resposta. Vale também para o modo clássico.',
  mode:'Observador não responde. Conversa mantém o diálogo dirigido à IA. Participativo pode responder ao contexto quando a opção “só quando chamado” estiver desligada.',
  onlyWhenCalled:'Exige um nome de chamada em cada fala antes de liberar a resposta.',
  wakeWords:'Nomes que chamam a IA nos três idiomas, separados por vírgulas. Ex.: Neve, Neva7.',
  profile:'Define o estilo base do Live. Não altera as permissões nem os limites.',
  personality:'Complementa o perfil do Live com seu jeito de conversar; use Personalizado para escrever tudo.',
  humor:'De 0 a 100: quanto humor sugerir nas respostas.',energy:'De 0 a 100: intensidade e entusiasmo da conversa.',curiosity:'De 0 a 100: tendência a fazer perguntas sobre o assunto.',spontaneity:'De 0 a 100: naturalidade e iniciativa sugeridas; as regras de participação ainda valem.',formality:'De 0 a 100: de informal a formal.',sarcasm:'De 0 a 100: frequência sugerida de ironia.',concision:'De 0 a 100: valores maiores pedem respostas mais curtas.',
  voice:'Nome da voz nativa do Gemini, como Aoede. A mesma voz pode falar nos três idiomas.',fallbackVoice:'Voz Edge para português no Cascade. Espanhol usa Elvira e inglês usa Aria automaticamente.',speed:'Ritmo do Live: sugestão no Gemini e velocidade aplicada no Cascade. 1 = normal.',volume:'Volume do áudio Live: 1 = 100%, 0 = mudo, 2 = 200%.',pitch:'Altera a altura da voz Live na saída. 0 mantém o tom; positivo fica mais agudo.',style:'Direção de fala para o Gemini, como calma, natural ou animada.',intensity:'De 0 a 100: intensidade emocional sugerida ao Gemini.',pronunciation:'Explique ao Gemini como pronunciar nomes, siglas ou palavras específicas.',
  silenceMs:'Silêncio necessário para considerar que a pessoa terminou. Menor responde mais rápido, mas pode cortar pausas.',incompleteMs:'Espera maior se a frase parece incompleta em PT, ES ou EN, ou se outra pessoa está falando.',vadMs:'Tempo de voz contínua para confirmar uma fala e interromper a resposta da IA.',vadThreshold:'Energia mínima do áudio considerada voz. Aumente se ruído estiver ativando a escuta.',maxUtteranceSeconds:'Limita quanto áudio uma pessoa pode enviar por turno.',maxResponseSeconds:'Encerra respostas faladas que excedem esta duração.',maxCharacters:'Pede respostas de texto curtas e limita o texto produzido no Cascade.',
  prebufferMs:'Áudio acumulado antes de tocar. Mais buffer tolera oscilações, mas demora mais a começar.',maxBufferMs:'Limite de áudio aguardando reprodução. Ao exceder, cancela o turno para não acumular atraso.',maxInputBufferMs:'Limite de áudio guardado enquanto o provider ainda está conectando.',maxPendingMs:'Descarta falas que aguardaram tempo demais na fila.',maxParticipants:'Quantidade máxima de participantes com fluxos de áudio ativos.',priorityUserId:'Discord ID que passa na frente quando há falas simultâneas na fila.',
  normalize:'Equilibra diferenças de volume do áudio Live.',compressor:'Reduz a diferença entre sons altos e baixos.',limiter:'Limita picos fortes de áudio na saída.',noiseReduction:'Reduz ruído no áudio gerado. Não filtra o microfone dos participantes.',equalizer:'Realça ou reduz a região de presença da voz em 3 kHz. 0 mantém o áudio.',
  cooldownMs:'Intervalo mínimo entre respostas da IA.',responsesPerMinute:'Teto de respostas por minuto para limitar excesso de participação.',interruptionsPerMinute:'Teto de interrupções; excesso coloca a conversa em modo silencioso.',
  allowUsers:'Só estes IDs podem participar. Vazio não restringe por usuário; use vírgulas.',denyUsers:'Bloqueia estes IDs de usuários, mesmo que estejam na lista permitida.',allowRoles:'Só participantes com uma destas funções podem participar. Vazio não restringe por função.',denyRoles:'Bloqueia participantes com qualquer uma destas funções. IDs separados por vírgulas.',
  tools:'clock consulta hora UTC; calculator calcula expressões. Lista vazia desliga ferramentas.',toolUsers:'IDs que podem usar ferramentas. É preciso autorizar por usuário ou função.',toolRoles:'IDs de funções autorizadas a usar ferramentas; vazio não concede acesso por função.',
  retainTranscripts:'Mostra o texto final da conversa na sessão em memória; não grava áudio.',permanentMemory:'Permite salvar notas manuais para usuários autorizados. O modelo não grava notas sozinho.',memoryUsers:'IDs que autorizaram memória permanente. Vazio impede salvar notas.',clearOnLeave:'Apaga o contexto ao sair. Desligado permite reter até cinco sessões nesta execução.',maxHistory:'Quantidade de turnos recentes enviados como contexto.',maxSummaryChars:'Limite do resumo extrativo dos turnos antigos.',
  reconnectAttempts:'Quantas vezes tentar reconectar o provider antes de entrar em proteção ou fallback.',idleSessionSeconds:'Fecha conexões com o provider após este tempo sem uso; reabre na próxima fala.',watchdogMb:'Ativa proteção se a memória do processo superar este limite.',watchdogLagMs:'Ativa proteção se o processo ficar atrasado por este tempo.',developer:'Inclui eventos técnicos adicionais na timeline, sem conteúdo de áudio.',inputPrice:'Preço do milhão de tokens de áudio de entrada no seu contrato. Zero deixa a estimativa sem preço.',outputPrice:'Preço do milhão de tokens de áudio de saída no seu contrato. Não representa cobrança em tempo real.',systemPrompt:'Instruções de comportamento do Live. A política de idiomas escolhida acima continua valendo.',autoJoinGuild:'ID do servidor em que o bot oficial deve entrar automaticamente ao conectar.',autoJoinChannel:'ID da call para entrada automática. Preencha também o servidor; vazio desativa a entrada automática.'
};
