// Headless Chrome fallback for local UI QA when the in-app Browser is unavailable.
// Starts its own in-memory preview. Never connects to the user's running bot.
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const assert=require('node:assert/strict');
const WebSocket=require('ws');
const {WebPanel}=require('../src/web-panel');
const {previewController}=require('./live-preview-fixture');
const chrome=process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const root=path.resolve(__dirname,'..');
const proc=spawn(chrome,['--headless','--disable-gpu','--disable-background-networking','--no-first-run','--no-default-browser-check',
  '--remote-debugging-port=0','--user-data-dir='+path.join(root,'.preview-chrome-qa')],{windowsHide:true});
let socket,timer,server,preview,recordingRoot,sequence=0;const requests=new Map(),errors=[];
function command(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++sequence;const deadline=setTimeout(()=>{requests.delete(id);reject(new Error('CDP timeout: '+method));},15000);requests.set(id,{resolve:value=>{clearTimeout(deadline);resolve(value);},reject:error=>{clearTimeout(deadline);reject(error);}});socket.send(JSON.stringify({id,method,params,sessionId}));});}
(async()=>{
  recordingRoot=fs.mkdtempSync(path.join(os.tmpdir(),'neva-recording-ui-'));preview=previewController(true,{recordingRoot});
  server=new WebPanel(preview,{port:0});const url=await server.start();console.log('Prévia isolada iniciada.');
  const endpoint=await new Promise((resolve,reject)=>{
    let stderr='';timer=setTimeout(()=>reject(new Error('Chrome não iniciou em 15 segundos.')),15000);
    proc.on('error',reject);proc.stderr.on('data',chunk=>{stderr=(stderr+chunk).slice(-10000);const match=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match){clearTimeout(timer);resolve(match[1]);}});
  });
  socket=new WebSocket(endpoint);await new Promise((resolve,reject)=>{socket.once('open',resolve);socket.once('error',reject);});
  socket.on('message',raw=>{const m=JSON.parse(raw);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id){const pending=requests.get(m.id);requests.delete(m.id);if(pending)m.error?pending.reject(new Error(m.error.message)):pending.resolve(m.result);}});
  const {targetId}=await command('Target.createTarget',{url:'about:blank'});
  const {sessionId}=await command('Target.attachToTarget',{targetId,flatten:true});
  const page=(method,params={})=>command(method,params,sessionId);
  const evaluate=async expression=>{const result=await page('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text);return result.result?.value;};
  const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw new Error('UI não atingiu o estado esperado: '+expression);};
  await page('Page.enable');await page('Runtime.enable');
  await page('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  await page('Page.navigate',{url});
  await wait("document.querySelectorAll('#navigation a').length===21");
  console.log('Painel carregado; verificando navegação.');
  const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const fill=async(selector,value,event='input')=>evaluate(`{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event(${JSON.stringify(event)},{bubbles:true}));}`);
  const navigate=async view=>{await click(`#navigation a[href="#${view}"]`);await wait(`document.querySelector('#navigation a[aria-current="page"]').hash==='#${view}'`);};
  const feedback=part=>wait(`document.querySelector('#feedback').textContent.includes(${JSON.stringify(part)}) && !classicBusy && !busy`);
  const links=await evaluate("Array.from(document.querySelectorAll('#navigation a'),a=>a.getAttribute('href'))");
  for(const href of links){
    await evaluate(`document.querySelector('#navigation a[href="${href}"]').click()`);
    await wait(`document.querySelector('#navigation a[aria-current="page"]').getAttribute('href')===${JSON.stringify(href)}`);
    assert.ok(await evaluate("document.querySelector('#content').children.length>0"));
    assert.ok(await evaluate("Array.from(document.querySelectorAll('[data-setting]')).every(el=>el.closest('.field').querySelector('small')?.textContent.length>10)"),'Missing setting description: '+href);
  }
  await evaluate("document.querySelector('#navigation a[href=\"#intelligence\"]').click()");
  await wait("!!document.querySelector('#f-mode')");
  await evaluate("document.querySelector('#f-mode').value='observer';document.querySelector('#f-mode').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#save').click()");
  await wait("document.querySelector('#feedback').textContent.includes('Configuração salva') && document.querySelector('#save').disabled");
  await fill('#f-replyLanguage','es');await click('#save');await wait("data.config.replyLanguage==='es' && !busy");
  await fill('#f-replyLanguage','auto');await click('#save');await wait("data.config.replyLanguage==='auto' && !busy");
  await evaluate("document.querySelector('#navigation a[href=\"#lab\"]').click()");
  await wait("!!document.querySelector('#runLab')");
  await evaluate("document.querySelector('#labText').value='Neve, eu queria, mas';document.querySelector('#runLab').click()");
  await wait("document.querySelector('#labResult').textContent.includes('1600')");
  assert.ok(await evaluate("document.querySelector('#labResult').textContent.includes('Responderia: não')"));
  console.log('Idiomas e laboratório verificados; verificando controles clássicos.');
  await fill('#guild','demo','change');await wait("status.guildId==='demo' && document.querySelector('#channel').options.length===2");
  await fill('#textChannel','text','change');await wait("status.textChannelId==='text'");
  await fill('#channel','voice','change');await click('#join');await wait('status.inCall===true');
  await navigate('recordings');await click('[data-classic="recordingStart"]');await wait('!!status.recording && !classicBusy');
  assert.ok(await evaluate('!document.querySelector("#recordingBanner").hidden'));
  await click('[data-classic="recordingStop"]');await wait('!status.recording && !classicBusy');
  await wait('!!document.querySelector("#recordingFiles audio")');
  await evaluate('window.qaAudio=document.querySelector("#recordingFiles audio");qaAudio.load()');await wait('qaAudio.readyState>=1');
  assert.ok(await evaluate('qaAudio.duration>0'));
  await evaluate('loadRecordings()');assert.ok(await evaluate('qaAudio===document.querySelector("#recordingFiles audio")'));
  const download=await evaluate('(async()=>{const r=await fetch(document.querySelector("#recordingFiles a[download]").href);return {status:r.status,bytes:(await r.arrayBuffer()).byteLength,disposition:r.headers.get("content-disposition")};})()');
  assert.equal(download.status,200);assert.ok(download.bytes>44);assert.ok(download.disposition.includes('attachment'));
  fs.writeFileSync(path.join(root,'recording-dashboard.png'),Buffer.from((await page('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await navigate('voice');await fill('#speechText','Hola, ¿cómo estás?');await click('[data-classic="say"]');await feedback('Áudio reproduzido');
  await click('[data-classic="repeat"]');await feedback('Última frase repetida');
  await fill('#voiceFilter','masculino','change');await fill('#classicVoice','antonio','change');await wait("status.voice==='antonio' && !classicBusy");
  await fill('#classicSpeed','1.25','change');await wait('status.speed===1.25 && !classicBusy');
  await navigate('personality');await fill('#classicEmotion','feliz','change');await wait("status.emotion==='feliz' && !classicBusy");
  await fill('#interactionSetting','Faça perguntas curtas.');await click('[data-classic="interaction"]');await feedback('Ajustes de interação salvos');
  await fill('#customEmotionSetting','Uma narradora calma.');await click('[data-classic="customEmotion"]');await feedback('Personalidade personalizada salva');
  await navigate('music');await fill('#musicQuery','Faixa de demonstração');await click('[data-classic="play"]');await feedback('Adicionado à fila');assert.ok(await evaluate("document.querySelector('[data-classic-live=queue]').textContent.includes('Faixa de demonstração')"));
  await fill('#musicVolume','65','change');await wait('status.volume===65 && !classicBusy');await click('[data-classic="stopMusic"]');await feedback('Música parada');
  await navigate('messages');await fill('#chatText','Hello, everyone!');await click('[data-classic="send"]');await feedback('Mensagem enviada');
  await fill('#memberQuery','Ana');await click('#searchMembers');await feedback('pessoa(s) encontrada(s)');await fill('#memberSelect','234567890123456789','change');await click('[data-classic="mention"]');await feedback('Ana Demo foi mencionado');
  await click('#checkMessageAccess');await wait("document.querySelector('#messageAccess').textContent.includes('estão liberadas')");
  assert.ok(await evaluate("document.querySelector('#memberSelect').textContent.includes('@Ana Demo')"));
  await fill('#memberQuery','234567890123456789');await click('#searchMembers');await wait("!memberSearchBusy && document.querySelector('#memberSelect').options.length===2");
  assert.ok(await evaluate("document.querySelector('#memberSearchStatus').textContent.includes('1 pessoa(s)')"));
  const sendMessage=preview.discord.sendMessage,rest=preview.discord.rest;
  preview.discord.sendMessage=async()=>{throw require('../src/discord-errors').discordRestError(403,{code:50013},'/channels/text/messages','POST');};
  await click('[data-classic="send"]');await wait("!classicBusy && document.querySelector('#messageSendError').textContent.includes('Discord 50013')");
  preview.discord.rest=async route=>route==='/channels/text'?{id:'text',type:0,guild_id:'demo',permission_overwrites:[{id:'demo',type:0,deny:'2048',allow:'0'}]}:rest(route);
  await click('#checkMessageAccess');await wait("document.querySelector('#messageAccess').textContent.includes('Envio bloqueado: Enviar mensagens')");
  preview.discord.sendMessage=sendMessage;preview.discord.rest=rest;
  fs.writeFileSync(path.join(root,'messages-dashboard.png'),Buffer.from((await page('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await click('[data-classic="summarize"]');await feedback('Resumo simulado');
  console.log('Voz, música e mensagens verificadas; verificando bloqueios e conexão.');
  await navigate('automation');await click('[data-classic="autoJoin"]');await wait('status.autoJoin===true && !classicBusy');
  await navigate('recordings');await click('[data-classic="recordingStart"]');await wait('!!status.recording && !classicBusy');
  await click('[data-control="safe"]');await wait("data.config.safeMode && document.querySelector('#notice [data-control=resume]')");assert.ok(await evaluate('document.querySelector("#join").disabled'));
  await evaluate('poll()');assert.ok(await evaluate('!status.recording'));
  await click('#notice [data-control="resume"]');await wait('!data.config.safeMode && !busy');
  await click('[data-control="kill"]');await wait("data.config.killed && document.querySelector('#notice').textContent.includes('Kill Switch ativo')");
  await click('#notice [data-control="resume"]');await wait('!data.config.killed && !busy');await evaluate('poll()');assert.ok(await evaluate('!status.inCall'));
  await navigate('connection');await fill('#connectionToken','fixture-token-not-real');await evaluate("document.querySelector('#connectionForm').requestSubmit()");await feedback('Conexão salva');assert.equal(await evaluate("document.querySelector('#connectionToken').value"),'');
  await fill('#presenceName','Conversando na prévia');await evaluate("document.querySelector('#presenceForm').requestSubmit()");await feedback('Atividade do bot atualizada');
  await evaluate("document.querySelector('#navigation a[href=\"#pipeline\"]').click()");
  await wait("document.querySelector('h1').textContent==='O ritmo da conversa.'");
  fs.writeFileSync(path.join(root,'live-dashboard.png'),Buffer.from((await page('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await page('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  for(const href of links){await navigate(href.slice(1));const size=await evaluate('({width:innerWidth,content:document.documentElement.scrollWidth})');assert.ok(size.content<=size.width,`Overflow ${href}: ${JSON.stringify(size)}`);}
  await evaluate("document.querySelector('#navigation a[href=\"#security\"]').click()");
  await wait("document.querySelector('h1').textContent==='Você está no controle.'");
  const size=await evaluate("({width:innerWidth,content:document.documentElement.scrollWidth})");
  fs.writeFileSync(path.join(root,'live-dashboard-mobile.png'),Buffer.from((await page('Page.captureScreenshot',{format:'png'})).data,'base64'));
  assert.ok(size.content<=size.width,`Overflow mobile: ${JSON.stringify(size)}`);
  assert.equal(errors.length,0,JSON.stringify(errors));
  console.log('OK: 21 áreas desktop/mobile; gravação, player WAV, download, idiomas, voz, música, mensagens, conexão e proteções verificados sem Discord real.');
  await command('Browser.close');
})().catch(error=>{console.error(error.message);process.exitCode=1;}).finally(async()=>{clearTimeout(timer);socket?.close();proc.kill();await server?.stop();await preview?.voice.recordings?.close();if(recordingRoot&&path.resolve(recordingRoot).startsWith(path.resolve(path.join(os.tmpdir(),'neva-recording-ui-'))))fs.rmSync(recordingRoot,{recursive:true,force:true});});
